-- Поиск дерева исходников Linux и генерация .clangd для out-of-tree модулей.
-- Путь больше нигде не захардкожен: том может называться как угодно и быть
-- не смонтирован — конфиг это переживает.

local M = {}

local function looks_like_kernel(path)
  return path ~= nil and vim.uv.fs_stat(vim.fs.joinpath(path, "include/linux/kernel.h")) ~= nil
end

local cached

--- @return string|nil путь к дереву ядра, если оно доступно
function M.src()
  if cached ~= nil then
    return cached ~= false and cached or nil
  end

  local candidates = {}
  for _, env in ipairs { vim.env.KERNEL_SRC, vim.env.KERNELDIR } do
    if env and env ~= "" then
      table.insert(candidates, env)
    end
  end
  vim.list_extend(candidates, vim.fn.glob("/Volumes/*/linux-*", false, true))
  vim.list_extend(candidates, vim.fn.glob("~/src/linux*", false, true))
  -- svm: ~/linux/linux-6.19
  vim.list_extend(candidates, vim.fn.glob("~/linux/linux-*", false, true))

  for _, path in ipairs(candidates) do
    if looks_like_kernel(path) then
      cached = path
      return path
    end
  end

  cached = false
  return nil
end

--- Требует смонтированное дерево ядра, иначе ругается вместо тихого молчания.
function M.require_src()
  local src = M.src()
  if not src then
    vim.notify(
      "Kernel sources not found: смонтируй образ или задай $KERNEL_SRC",
      vim.log.levels.WARN
    )
  end
  return src
end

-- Корень модуля — каталог с Kbuild/Makefile, иначе cwd.
local function module_root()
  local start = vim.api.nvim_buf_get_name(0)
  if start == "" then
    start = vim.uv.cwd()
  end
  return vim.fs.root(start, { "Kbuild", "Makefile" }) or vim.uv.cwd()
end

local ARCH = "x86"

-- Kbuild собирает с -nostdinc и вручную добавляет каталог встроенных
-- заголовков компилятора (stddef.h, stdarg.h). Без него clang не разберёт
-- ни одного заголовка ядра.
local function clang_resource_include()
  -- Сначала заголовки, идущие в комплекте с самим clangd: версии должны
  -- совпадать, иначе он ругается на встроенные типы.
  local bundled = vim.fn.glob(
    vim.fs.joinpath(vim.fn.stdpath "data", "mason/packages/clangd/clangd_*/lib/clang/*/include"),
    false,
    true
  )
  if bundled[1] then
    return bundled[1]
  end
  local out = vim.fn.system { "clang", "-print-resource-dir" }
  if vim.v.shell_error == 0 then
    return vim.fs.joinpath(vim.trim(out), "include")
  end
  return nil
end

--- Пишет .clangd в корень модуля: без compile_commands.json clangd иначе
--- не находит ни одного заголовка ядра.
function M.write_clangd()
  local src = M.require_src()
  if not src then
    return
  end

  local root = module_root()
  local includes = {
    "include",
    "include/uapi",
    "include/generated",
    "include/generated/uapi",
    "arch/" .. ARCH .. "/include",
    "arch/" .. ARCH .. "/include/uapi",
    "arch/" .. ARCH .. "/include/generated",
    "arch/" .. ARCH .. "/include/generated/uapi",
  }

  local flags = {
    "--target=x86_64-linux-gnu",
    -- Без -xc clangd считает .h за Objective-C++ и отвергает -std=gnu18.
    "-xc",
    "-std=gnu18",
    "-nostdinc",
    "-D__KERNEL__",
    "-DMODULE",
    -- Kbuild собирается как `make type=lf` либо `type=sy`; без одного из этих
    -- define'ов половина ds_control скрыта под #ifdef.
    "-DLF_MODE",
    -- Безымянные поля структурного типа в заголовках ядра (struct ns_common).
    "-fms-extensions",
    "-I" .. root,
  }

  -- kconfig.h тянет include/generated/autoconf.h, а он появляется только
  -- после сборки. В голом клоне его нет, и -include просто всё сломает.
  if vim.uv.fs_stat(vim.fs.joinpath(src, "include/generated/autoconf.h")) then
    vim.list_extend(flags, {
      "-include",
      vim.fs.joinpath(src, "include/linux/kconfig.h"),
      "-include",
      vim.fs.joinpath(src, "include/linux/compiler_types.h"),
    })
  else
    vim.notify(
      "В дереве нет include/generated/autoconf.h — сначала `make defconfig && make prepare`.\n"
        .. "Пока сгенерирую .clangd без CONFIG_*: часть кода под ifdef будет серой.",
      vim.log.levels.WARN
    )
    vim.list_extend(flags, {
      "-include",
      vim.fs.joinpath(src, "include/linux/compiler_types.h"),
    })
  end

  local resource_include = clang_resource_include()
  if resource_include then
    table.insert(flags, "-I" .. resource_include)
  end
  for _, inc in ipairs(includes) do
    table.insert(flags, "-I" .. vim.fs.joinpath(src, inc))
  end
  for _, dir in ipairs { "utils", "utils/lock-free", "utils/sync" } do
    if vim.uv.fs_stat(vim.fs.joinpath(root, dir)) then
      table.insert(flags, "-I" .. vim.fs.joinpath(root, dir))
    end
  end

  local lines = { "# Generated by :KernelClangd — machine-specific, не коммить.", "CompileFlags:" }
  table.insert(lines, "  Compiler: clang")
  table.insert(lines, "  Add:")
  for _, flag in ipairs(flags) do
    table.insert(lines, "    - " .. flag)
  end
  -- gcc-only флаги из Kbuild, на которых clang спотыкается.
  table.insert(lines, "  Remove:")
  for _, flag in ipairs {
    "-mno-fp-ret-in-387",
    "-mpreferred-stack-boundary=*",
    "-mskip-rax-setup",
    "-mindirect-branch=*",
    "-mfunction-return=*",
    "-mrecord-mcount",
    "-fno-allow-store-data-races",
    "-fconserve-stack",
    "-fno-var-tracking-assignments",
    "-femit-struct-debug-baseonly",
    "-fsanitize=bounds-strict",
  } do
    table.insert(lines, "    - " .. flag)
  end
  vim.list_extend(lines, {
    "Diagnostics:",
    "  UnusedIncludes: None",
    "  MissingIncludes: None",
  })

  local out = vim.fs.joinpath(root, ".clangd")
  vim.fn.writefile(lines, out)
  vim.notify(".clangd written: " .. out .. "\nkernel: " .. src)

  for _, client in ipairs(vim.lsp.get_clients { name = "clangd" }) do
    client:stop()
  end
end

--- Готовит дерево ядра к индексации: обёртки asm/*.h, autoconf.h, timeconst.h,
--- bounds.h и asm-offsets.h. Штатный `make prepare` на macOS не проходит —
--- arch/x86/tools/relocs требует <elf.h>, которого в SDK нет.
function M.prepare()
  local src = M.require_src()
  if not src then
    return
  end

  local script = vim.fs.joinpath(vim.fn.stdpath "config", "scripts/kernel_prepare.py")
  if not vim.uv.fs_stat(script) then
    vim.notify("Нет " .. script, vim.log.levels.ERROR)
    return
  end

  local cmd = { "python3", script, src }
  local resource_include = clang_resource_include()
  if resource_include then
    table.insert(cmd, resource_include)
  end

  vim.notify("Готовлю дерево ядра, это займёт минуту: " .. src)
  vim.system(cmd, { text = true }, function(res)
    vim.schedule(function()
      local out = vim.trim((res.stdout or "") .. (res.stderr or ""))
      vim.notify(out, res.code == 0 and vim.log.levels.INFO or vim.log.levels.ERROR)
    end)
  end)
end

--- Строит cscope.out в корне дерева ядра. `make cscope` не годится: Kbuild
--- требует GNU make >= 4, а на macOS /usr/bin/make — 3.81. Индексируем всё,
--- кроме чужих архитектур, документации и tools/ — иначе база раздувается
--- втрое, а в выдаче дубли из arch/arm64, arch/mips и т.д.
function M.cscope()
  local src = M.require_src()
  if not src then
    return
  end

  local list = table.concat({
    "find . \\( -path ./arch -o -path ./Documentation -o -path ./tools",
    "-o -path ./scripts -o -path ./samples \\) -prune",
    "-o -name '*.[chS]' -print > cscope.files",
    "&& find arch/" .. ARCH .. " -name '*.[chS]' -print >> cscope.files",
    "&& cscope -bqk -i cscope.files -f cscope.out",
  }, " ")

  vim.notify("Строю cscope-базу ядра, это пара минут: " .. src)
  vim.system({ "sh", "-c", list }, { cwd = src, text = true }, function(res)
    vim.schedule(function()
      if res.code == 0 then
        vim.notify("cscope.out готов: " .. vim.fs.joinpath(src, "cscope.out"))
      else
        vim.notify("cscope упал:\n" .. (res.stderr or ""), vim.log.levels.ERROR)
      end
    end)
  end)
end

function M.setup()
  vim.api.nvim_create_user_command("KernelCscope", M.cscope, {
    desc = "Build cscope database for the kernel tree",
  })
  vim.api.nvim_create_user_command("KernelClangd", M.write_clangd, {
    desc = "Generate .clangd for an out-of-tree kernel module",
  })
  vim.api.nvim_create_user_command("KernelPrepare", M.prepare, {
    desc = "Generate kernel headers clangd needs (asm wrappers, autoconf, offsets)",
  })
  vim.api.nvim_create_user_command("KernelSrc", function()
    vim.notify(M.src() or "kernel sources not found")
  end, { desc = "Show detected kernel source tree" })
end

return M
