#!/usr/bin/env python3
"""Готовит дерево ядра к индексации clangd на macOS.

`make prepare` здесь не проходит: arch/x86/tools/relocs требует <elf.h>,
которого в macOS SDK нет. Но всё, что реально нужно clangd, добывается
без хост-тулзов:

  1. обёртки asm/*.h -> asm-generic/*.h (их пишет scripts/Makefile.asm-headers);
  2. .config и include/generated/autoconf.h (kconfig собирается на хосте,
     нужен только линкер lld вместо ld от Apple);
  3. include/generated/{bounds,asm-offsets,rq-offsets}.h — исходники для них
     компилируются обычным clang с --target=x86_64-linux-gnu.

Usage: kernel_prepare.py <kernel-src> [clang-resource-include]
"""

import pathlib
import re
import shutil
import subprocess
import sys

ARCH = "x86"


def sh(args, cwd, **kw):
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, **kw)


def listed(path, key):
    if not path.exists():
        return []
    return re.findall(r"^%s\s*\+=\s*(\S+)" % key, path.read_text(), re.M)


def gen_wrappers(root):
    """Однострочные обёртки, которые обычно генерирует Kbuild."""
    total = 0
    for arch_kbuild, generic_kbuild, arch_dir, out_dir in (
        (
            f"arch/{ARCH}/include/asm/Kbuild",
            "include/asm-generic/Kbuild",
            f"arch/{ARCH}/include/asm",
            f"arch/{ARCH}/include/generated/asm",
        ),
        (
            f"arch/{ARCH}/include/uapi/asm/Kbuild",
            "include/uapi/asm-generic/Kbuild",
            f"arch/{ARCH}/include/uapi/asm",
            f"arch/{ARCH}/include/generated/uapi/asm",
        ),
    ):
        names = set(listed(root / arch_kbuild, "generic-y"))
        names |= set(listed(root / generic_kbuild, "mandatory-y"))
        out = root / out_dir
        out.mkdir(parents=True, exist_ok=True)
        for name in sorted(names):
            if (root / arch_dir / name).exists() or (out / name).exists():
                continue  # у арха есть свой заголовок либо обёртка уже на месте
            (out / name).write_text(f"#include <asm-generic/{name}>\n")
            total += 1
    return total


def gen_config(root):
    if (root / "include/generated/autoconf.h").exists():
        return "уже есть"
    make = shutil.which("gmake") or shutil.which("make")
    if not make:
        return "пропущено: нет gmake"
    if not shutil.which("ld.lld"):
        return "пропущено: нет ld.lld (brew install lld)"
    # LLVM=1 — иначе Kconfig.include отвергает ld от Apple.
    env = ["ARCH=x86_64", "LLVM=1", "LLVM_IAS=1"]
    for target in ("x86_64_defconfig", "syncconfig"):
        res = sh([make, *env, target], root)
        if res.returncode != 0:
            return f"ошибка на {target}: {res.stderr.strip().splitlines()[-1:]}"
    return "сгенерирован"


def gen_timeconst(root):
    """include/generated/timeconst.h: Kbuild гонит kernel/time/timeconst.bc через bc."""
    out = root / "include/generated/timeconst.h"
    if out.exists():
        return "уже есть"
    src = root / "kernel/time/timeconst.bc"
    config = root / ".config"
    if not src.exists() or not config.exists():
        return "пропущено: нет timeconst.bc или .config"
    hz = None
    for line in config.read_text().splitlines():
        if line.startswith("CONFIG_HZ="):
            hz = line.split("=", 1)[1].strip()
    if not hz or not shutil.which("bc"):
        return "пропущено: нет CONFIG_HZ или bc"
    res = subprocess.run(
        ["bc", "-q", str(src)], input=hz + "\n", capture_output=True, text=True, cwd=root
    )
    if res.returncode != 0 or "KERNEL_TIMECONST_H" not in res.stdout:
        return "ошибка bc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(res.stdout)
    return f"сгенерирован (HZ={hz})"


OFFSET_SOURCES = (
    ("kernel/bounds.c", "include/generated/bounds.h", "__LINUX_BOUNDS_H__"),
    (
        f"arch/{ARCH}/kernel/asm-offsets.c",
        "include/generated/asm-offsets.h",
        "__ASM_OFFSETS_H__",
    ),
    ("kernel/sched/rq-offsets.c", "include/generated/rq-offsets.h", "__RQ_OFFSETS_H__"),
)

ASCII = re.compile(r'^\s*\.ascii\s+"(.*)"')


def offsets_to_header(asm_text, guard):
    """Повторяет sed-offsets из scripts/Kbuild.include."""
    lines = [f"#ifndef {guard}", f"#define {guard}", "/* Generated by kernel_prepare.py */", ""]
    for raw in asm_text.splitlines():
        m = ASCII.match(raw)
        if not m:
            continue
        entry = m.group(1).encode().decode("unicode_escape")
        if not entry.startswith("->"):
            continue
        entry = entry[2:]
        if entry.startswith("#"):
            lines.append(f"/* {entry[1:].strip()} */")
            continue
        if not entry.strip():
            lines.append("")
            continue
        parts = entry.split(" ", 2)
        name = parts[0]
        value = parts[1].lstrip("$#") if len(parts) > 1 else ""
        comment = parts[2] if len(parts) > 2 else ""
        lines.append(f"#define {name} {value}" + (f" /* {comment} */" if comment else ""))
    lines += ["", f"#endif /* {guard} */"]
    return "\n".join(lines) + "\n"


def gen_offsets(root, resource_include):
    includes = [
        "include",
        "include/uapi",
        "include/generated",
        "include/generated/uapi",
        f"arch/{ARCH}/include",
        f"arch/{ARCH}/include/uapi",
        f"arch/{ARCH}/include/generated",
        f"arch/{ARCH}/include/generated/uapi",
    ]
    flags = [
        "--target=x86_64-linux-gnu",
        "-S",
        "-nostdinc",
        "-std=gnu18",
        "-D__KERNEL__",
        # Ядро использует безымянные поля структурного типа (struct ns_common),
        # без этого флага они не разбираются.
        "-fms-extensions",
        "-w",
        "-include",
        "include/linux/kconfig.h",
        "-include",
        "include/linux/compiler_types.h",
    ]
    if resource_include:
        flags.append("-I" + resource_include)
    flags += ["-I" + inc for inc in includes]

    results = []
    for src, out, guard in OFFSET_SOURCES:
        if not (root / src).exists():
            results.append(f"{out}: нет исходника {src}")
            continue
        res = sh(["clang", *flags, "-o", "-", src], root)
        if res.returncode != 0 or "->" not in res.stdout:
            # Заглушка: сами значения нужны только .S-файлам и inline asm,
            # а вот отсутствие файла рушит разбор всей цепочки заголовков.
            tail = (res.stderr.strip().splitlines() or ["?"])[-1]
            (root / out).write_text(
                f"#ifndef {guard}\n#define {guard}\n"
                f"/* Stub: {src} не собрался этим clang ({tail}).\n"
                f" * Значения нужны только ассемблеру; для индексации хватает наличия файла.\n"
                f" * Настоящий файл появится после сборки ядра на Linux. */\n"
                f"#endif /* {guard} */\n"
            )
            results.append(f"{out}: заглушка ({tail})")
            continue
        (root / out).write_text(offsets_to_header(res.stdout, guard))
        results.append(f"{out}: ok")
    return results


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: kernel_prepare.py <kernel-src> [clang-resource-include]")
    root = pathlib.Path(sys.argv[1]).expanduser().resolve()
    resource_include = sys.argv[2] if len(sys.argv) > 2 else None
    if not (root / "include/linux/kernel.h").exists():
        sys.exit(f"не похоже на дерево ядра: {root}")

    print(f"дерево: {root}")
    print(f"обёртки asm/: {gen_wrappers(root)} шт.")
    print(f"autoconf.h: {gen_config(root)}")
    print(f"timeconst.h: {gen_timeconst(root)}")
    # bounds.h нужен asm-offsets.c, поэтому порядок в OFFSET_SOURCES важен.
    for line in gen_offsets(root, resource_include):
        print(f"  {line}")


if __name__ == "__main__":
    main()
